# Python For ML

## Numpy for Python
### Allows advanced mathematical operations
### Faster operations

#### importing numpy as np

In [ ]:
import numpy as np

### np.array() method is used to create numpy array

In [ ]:
np_array = np.array(range(1,1000))
np_array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [ ]:
type(np_array)

numpy.ndarray

### varName.shape method is returns a tuple of the dimenions of the array

In [ ]:
np_array.shape

(999,)

In [ ]:
list1 = [1,2,3,4,5]
print(np.array(list1))

[1 2 3 4 5]


### creating a multi dimensional array default dtype is int and externally can change the type by dtype = float

In [ ]:
arr = np.array([(1,2,3,4),(4,5,6,7)],dtype=float)
print(arr)
print("shape: ",arr.shape)

[[1. 2. 3. 4.]
 [4. 5. 6. 7.]]
shape:  (2, 4)


### Initial Placeholders

In [ ]:
#numpy arr of zeros np.zeroes((rows,cols))
z = np.zeros((4,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#numpy arr of ones np.ones((rows,cols))
z = np.ones((3,3))
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# arr with custom initial values
# np.full((row,col),value)
z = np.full((3,4),5)
z

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### creating an identity matrix using eye matrix. it accepts only one integer for setting the dimesions . bcz , identity matrix is a n*n

In [ ]:
i = np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### numpy array of random values

In [ ]:
#(row,col)
# random method generates values randomly in 0 to 1
x = np.random.random((4,3))
x

array([[0.60083855, 0.01278501, 0.98870603],
       [0.0878241 , 0.73557667, 0.57040249],
       [0.97085736, 0.80910553, 0.69852291],
       [0.09915356, 0.34796271, 0.39585984]])

In [ ]:
### for discrete values
# random.randint(start,end,(row,col))
x = np.random.randint(10,101,(3,3))
x

array([[27, 20, 92],
       [37, 38, 78],
       [74, 77, 10]])

In [ ]:
# array of evenly spaced
#(start,end,number of values)
x = np.linspace(20,40,5)
x

array([20., 25., 30., 35., 40.])

In [ ]:
# array of evently spaced with custom step size
#(start,end,step)
x = np.arange(10,30,5)
x

array([10, 15, 20, 25])

## analysing a numpy array

In [ ]:
c = np.random.randint(10,100,(5,5))
c

array([[89, 47, 70, 24, 80],
       [87, 43, 36, 40, 94],
       [28, 48, 86, 51, 21],
       [71, 56, 95, 64, 79],
       [82, 41, 74, 51, 76]])

In [ ]:
## array dimension
c.shape

(5, 5)

In [ ]:
## number of dimensions
c.ndim

2

In [ ]:
# number of elements
c.size

25

In [ ]:
# checking the dtype of values in the array
print(c.dtype)

int64


# **Mathematical operations on numpy array**

# addition b/n two lists returns the concat of the two lists in normal arr

In [ ]:
list1 = [1,2,3,4,5]
list2 = [1,2,3,4,5]
print(list1+list2)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# numpy performs element wise addition. if we use + b/n two arrays
and also same for all mathematical operations

In [ ]:
list1 = np.array(list1)
list2 = np.array(list2)
print(list1+list2)

[ 2  4  6  8 10]


In [ ]:
#subtraction

list1 = np.array(list1)
list2 = np.array(list2)
print(list1-list2)

[0 0 0 0 0]


In [ ]:
#multiplication

list1 = np.array(list1)
list2 = np.array(list2)

print(list1*list2)

[ 1  4  9 16 25]


In [ ]:
list1 = np.array(list1)
list2 = np.array(list2)
print(list1/list2)

[1. 1. 1. 1. 1.]


# builtin numpy method to add

In [ ]:
print(np.add(list1,list2))
print(np.subtract(list1,list2))
print(np.multiply(list1,list2))
print(np.divide(list1,list2))

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]


# **Array manlipulations**

In [ ]:
# random valued arr

x = np.random.randint(1,1000,(3,4))
print(x)

[[245 701 998 105]
 [839 274 707 924]
 [246 147 669 666]]
[[245 839 246]
 [701 274 147]
 [998 707 669]
 [105 924 666]]


## transposing the array

In [ ]:
print(np.transpose(x)) # same as x.T

[[245 839 246]
 [701 274 147]
 [998 707 669]
 [105 924 666]]


### reshaping the array

## the shape of the resulatant array should be convertable

In [ ]:
print(x.shape)
print(x.reshape(2,6))

(3, 4)
[[245 701 998 105 839 274]
 [707 924 246 147 669 666]]


## Flattening the np array

In [ ]:
#flattening using the np.ravel(arr) method
print(np.ravel(x))

[245 701 998 105 839 274 707 924 246 147 669 666]


# **Pandas for ML**

### pandas library is used for data processing and analysis

### pandas daraframe is 2d ds which contains rows and columns with labelled acess to rows and columns

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/diabetes.csv")

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

## import boston dataset from sklearn datasets

### in sklearn datasets are of type bunch.
### the data key contains the data and the feature_names contains the parameters or fields of data(columns)

In [ ]:
import pandas as pd
from sklearn.datasets import load_diabetes

# Load the diabetes dataset
diabetes = load_diabetes()

In [ ]:
diabetes.feature_names

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

### inorder to convert the bunch into the pandas df, Dataframe(data,column names)

In [ ]:


# Create a DataFrame from the data
diabetes_df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)

# Add the target column to the DataFrame
diabetes_df['target'] = diabetes.target

# Display the first few rows of the DataFrame
print(diabetes_df.head())

        age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019907 -0.017646   151.0  
1 -0.039493 -0.068332 -0.092204    75.0  
2 -0.002592  0.002861 -0.025930   141.0  
3  0.034309  0.022688 -0.009362   206.0  
4 -0.002592 -0.031988 -0.046641   135.0  


### function to read the data from a excel

In [ ]:
excel_df = pd.read_excel()

## Exporting the pandas dataframe to a csv file. it converts and creates a new file

In [ ]:
diabetes_df.to_csv("diabetes.csv")

## Exporting the pandas dataframe to a csv file. it converts and creates a new file

In [ ]:
df.to_excel("diabetes.xlsx")

### creating a random datafram

In [ ]:
random_df = pd.DataFrame(np.random.randint(10,200,(20,5)),columns = ["A","B","C","D","E"])
random_df

A    B    C    D    E
0    24  137  186   28  111
1    18  180  198  150  149
2   176   11   24   68  166
3   179   58  115  145   57
4    95  119   86   26   49
5    69   55   77  175  182
6    97   26  182  142  188
7   156  138   32   62  173
8    26  195   16   75   63
9    92  101   17  178   47
10   65  131  138   62   35
11   32   24  114   66   45
12  101   26   24   61   57
13  166   82   35  142  108
14   14  120  135   95  108
15   70   88  156   17  176
16   78  105   23  173  122
17  104  135   57   88  128
18  155  167   47  142   84
19   93  105  129   96   79

# inspecting the df

#### shape of the df

In [ ]:
diabetes_df.shape

(442, 11)

#### information about the df

In [ ]:
diabetes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
 10  target  442 non-null    float64
dtypes: float64(11)
memory usage: 38.1 KB


### All statistical data related to the df

In [ ]:
diabetes_df.describe()

age           sex           bmi            bp            s1  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean  -2.511817e-19  1.230790e-17 -2.245564e-16 -4.797570e-17 -1.381499e-17   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.072256e-01 -4.464164e-02 -9.027530e-02 -1.123988e-01 -1.267807e-01   
25%   -3.729927e-02 -4.464164e-02 -3.422907e-02 -3.665608e-02 -3.424784e-02   
50%    5.383060e-03 -4.464164e-02 -7.283766e-03 -5.670422e-03 -4.320866e-03   
75%    3.807591e-02  5.068012e-02  3.124802e-02  3.564379e-02  2.835801e-02   
max    1.107267e-01  5.068012e-02  1.705552e-01  1.320436e-01  1.539137e-01   

                 s2            s3            s4            s5            s6  \
count  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02  4.420000e+02   
mean   3.918434e-17 -5.777179e-18 -9.042540e-18  9.293722e-17  1.130318e-17   
std    4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02  4.761905e-02   
min   -1.156131e-01 -1.023071e-01 -7.639450e-02 -1.260971e-01 -1.377672e-01   
25%   -3.035840e-02 -3.511716e-02 -3.949338e-02 -3.324559e-02 -3.317903e-02   
50%   -3.819065e-03 -6.584468e-03 -2.592262e-03 -1.947171e-03 -1.077698e-03   
75%    2.984439e-02  2.931150e-02  3.430886e-02  3.243232e-02  2.791705e-02   
max    1.987880e-01  1.811791e-01  1.852344e-01  1.335973e-01  1.356118e-01   

           target  
count  442.000000  
mean   152.133484  
std     77.093005  
min     25.000000  
25%     87.000000  
50%    140.500000  
75%    211.500000  
max    346.000000

## finding the number of missing values in each colum

In [ ]:
# sum() method returns the cnt of each column
diabetes_df.isnull().sum()

age       0
sex       0
bmi       0
bp        0
s1        0
s2        0
s3        0
s4        0
s5        0
s6        0
target    0
dtype: int64

# self task counting the diabetes patients from the df whose outcome val is 1

In [ ]:
count = 0
df = pd.read_csv("/content/diabetes.csv")
df.keys()

for res in df["Outcome"]:
  if(res == 1):
    count += 1
print("No of diabets: ",count)

No of diabets:  268


**Default function for it**

In [ ]:
res = df.value_counts("Outcome")
print(res)
print("no of diabetes: ",res[1])

Outcome
0    500
1    268
Name: count, dtype: int64
no of diabetes:  268


### grouping the values based on mean

In [ ]:
df.groupby("Outcome").mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

### Statistical measures

In [ ]:
# count or number of values in each column
df.count()

Pregnancies                 768
Glucose                     768
BloodPressure               768
SkinThickness               768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
dtype: int64

In [ ]:
#mean value column wise
df.mean()

Pregnancies                   3.845052
Glucose                     120.894531
BloodPressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
Age                          33.240885
Outcome                       0.348958
dtype: float64

In [ ]:
# standard deviation column wise
df.std()

Pregnancies                   3.369578
Glucose                      31.972618
BloodPressure                19.355807
SkinThickness                15.952218
Insulin                     115.244002
BMI                           7.884160
DiabetesPedigreeFunction      0.331329
Age                          11.760232
Outcome                       0.476951
dtype: float64

In [ ]:
# min value in each column
df.min()

Pregnancies                  0.000
Glucose                      0.000
BloodPressure                0.000
SkinThickness                0.000
Insulin                      0.000
BMI                          0.000
DiabetesPedigreeFunction     0.078
Age                         21.000
Outcome                      0.000
dtype: float64

In [ ]:
# all in one
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

# Manipulating a df

In [ ]:
#adding new column
age = df["Age"]
random_df['age'] = age

In [ ]:
random_df

A    B    C    D    E    age
14   120  135  95   108  51     1
18   180  198  150  149  31     1
176  11   24   68   166  32     1
166  82   35   142  108  59     1
156  138  32   62   173  29     1
155  167  47   142  84   33     1
104  135  57   88   128  31     1
101  26   24   61   57   57     1
97   26   182  142  188  26     1
95   119  86   26   49   33     1
93   105  129  96   79   32     1
92   101  17   178  47   54     1
78   105  23   173  122  31     1
70   88   156  17   176  32     1
69   55   77   175  182  30     1
65   131  138  62   35   30     1
32   24   114  66   45   34     1
26   195  16   75   63   53     1
24   137  186  28   111  50     1
179  58   115  145  57   21     1
Name: count, dtype: int64


In [ ]:
random_df.describe()

A          B          C           D           E        age
count   20.000000   20.00000   20.00000   20.000000   20.000000  20.000000
mean    90.500000  100.15000   89.55000   99.550000  106.350000  37.450000
std     53.537493   53.62175   62.51945   52.213605   52.044793  11.591626
min     14.000000   11.00000   16.00000   17.000000   35.000000  21.000000
25%     56.750000   57.25000   30.00000   62.000000   57.000000  30.750000
50%     92.500000  105.00000   81.50000   91.500000  108.000000  32.000000
75%    116.750000  135.50000  135.75000  142.750000  153.250000  50.250000
max    179.000000  195.00000  198.00000  178.000000  188.000000  59.000000

In [ ]:
## removing a row
random_df.drop(index=1)


A    B    C    D    E  age
0    24  137  186   28  111   50
2   176   11   24   68  166   32
3   179   58  115  145   57   21
4    95  119   86   26   49   33
5    69   55   77  175  182   30
6    97   26  182  142  188   26
7   156  138   32   62  173   29
8    26  195   16   75   63   53
9    92  101   17  178   47   54
10   65  131  138   62   35   30
11   32   24  114   66   45   34
12  101   26   24   61   57   57
13  166   82   35  142  108   59
14   14  120  135   95  108   51
15   70   88  156   17  176   32
16   78  105   23  173  122   31
17  104  135   57   88  128   31
18  155  167   47  142   84   33
19   93  105  129   96   79   32

In [ ]:
# add a parameter which changes the axis from horizontal to vertical
# if axis = 0,  removes rows default it is 0
# axis = 1 , removes particular column

random_df.drop('A',axis=1)

B    C    D    E  age
0   137  186   28  111   50
1   180  198  150  149   31
2    11   24   68  166   32
3    58  115  145   57   21
4   119   86   26   49   33
5    55   77  175  182   30
6    26  182  142  188   26
7   138   32   62  173   29
8   195   16   75   63   53
9   101   17  178   47   54
10  131  138   62   35   30
11   24  114   66   45   34
12   26   24   61   57   57
13   82   35  142  108   59
14  120  135   95  108   51
15   88  156   17  176   32
16  105   23  173  122   31
17  135   57   88  128   31
18  167   47  142   84   33
19  105  129   96   79   32

### correlation

## it is used to find the relation between the varaibles or columns

## there are 2 types of correlations
## +ve correlation -> if one variable rises . so, the depending also rises
## -ve correlation -> it is opposite to +ve

In [ ]:
#it gives all the correlation value to all other values
#if value is -ve then it is -ve corr
#else pos

df.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000